name: orange_wifi_control
description: >-
  Application mobile pour voir les appareils connectés à ton WiFi (routeur
  Orange Maroc / ZTE) et bloquer l'accès aux appareils non autorisés.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
